config/routes.rb
Rails.application.routes.draw do
  resources :restaurants

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
  end

  def params_restaurant
    params.require(:restaurant).permit(:name)
  end

  def create
    Restaurant.create(params_restaurant)
    redirect_to '/restaurants'
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(params_restaurant)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted'
    redirect_to '/restaurants'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AthleticYelp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/restaurants/edit.html.erb
<%= form_for @restaurant do |rest| %>
  <%= rest.label :name %>
  <%= rest.text_field :name %>
  <%= rest.submit %>
<% end %>

app/views/restaurants/index.html.erb
<% if @restaurants.length > 0 %>
  <% @restaurants.each do |restaurant| %>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
    <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
  <% end %>
<% else %>
  No restaurants yet
<% end %>

<a href="/restaurants/new">Add a restaurant</a>

app/views/restaurants/new.html.erb
<%= form_for Restaurant.new do |rest| %>
  <%= rest.label :name %>
  <%= rest.text_field :name %>
  <%= rest.submit %>
<% end %>

app/views/restaurants/show.html.erb
<%= @restaurant.name %>